---
spec/spec_helper.rb:
  mock_with: ':rspec'
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true

Gemfile:
  optional:
    ":development":
    - gem: puppet_litmus
      git: https://github.com/puppetlabs/puppet_litmus
      ref: main
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.5.0')
