---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: tamerz
  password:
    secure: "I8hvLQHmKqeq41zefBaHwIgWCgh7LFFYbc630NYMGdbsOlQ3d92UUM3Y4EMfCX5rB3CIgrwtCE7Aa6cAWuYjvzk4SR3frQm7Pv8DP/J9qKASbLDrUBW0qNN65ijuCk/CampU2lpk1xuO74qkPWO/q2hJFt5zSdACKGIjl3bSPgc6nHHTVaHpt8ojA08w4TrzSeYHI6hyWpR/2qyt0R5HjSyBh31bnNONXnH3Zj/VZH1rgI6J9/n2JlATNEKOjaqzrziQOgqhWT6TMkW/17sIDm4Q9T6ah1QXYWtyYHTSsbx20I8PNAyHKJyKN9G85esrVYZKxMy90OjFDcbcc6t8OY48Z0wtGhu9cm1ujlV5cT8i+qYzMZM9DwC0wxRm0H794xpCpTHoXSce2i/82MLelbC+ZcWHvHgH0j3ZVewyr5NGZrt05x0UQ2RcunWAeT9oOjSg32ntTis6Dn7D9fi+oli/obou/eNmtRwe97h1PVW/wCPlL3Jjwt0qhilBINenwL+dC7KvX8d/L2063V1EFnlRZ+LpbRl6g5IdC0sG9WRFzMMekzMwmA6td5iFtt7rwlcy9jkhP04UoZ5jqfxZ4TDjju011Il3B3R7C0LhH1CSrPUkNf7lSzYP8CRUieys9jg8rN0U54vwswjSok7H2a1Krj3sa3F2PpQo4DZhLag="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
